# 1. Build Stage (Compiles the Java code)
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# 2. Run Stage (Lighter image just to run the jar)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Copy the built JAR file from the previous stage
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]